# General
error_reporting_users: "@Gyd0x"
owner_ids:
  - "490122972124938240"
  - "891355078416543774"
cooldown: 20000
blacklist_time_out: 604800
bot:
  name: "Barkeep Kessing"
  icon: "https://gateway.pinata.cloud/ipfs/QmfDMuE67XLAkDJ1vmzzcffVvXupyJ5D4bh7vFpy8UQsaf"
  server_icon: "https://gateway.pinata.cloud/ipfs/QmRT1KRALWRbtwmmDVwGnwts3Qc6KCEwa7vtrWFvsY9DqB"

# Colors
colors:
  primary: "#FBE375"
  info: "#0EA5E9"
  error: "#FF0000"
  warning: "#E7C000"

# Sea creatures
sea_creatures:
  shrimp:
    high: 0.1
  crab:
    low: 0.1
    high: 1
  octopus:
    low: 1
    high: 3
  fish:
    low: 3
    high: 5
  dolphin:
    low: 5
    high: 10
  shark:
    low: 10
    high: 100
  whale:
    low: 100
    high: 500
  humpback:
    low: 500

# Responses
response:
  titles:
    - Adventurer
    - Traveller
    - Citizen
    - my guy
    - Ser
  small_tip:
    - As you wish.
    - As you require.
    - As you please!
    - Straight away.
    - At your service.
    - I’ll see what I can do.
    - I’ll be on my way.
    - Will do, %title%.
    - Yes, %title%.
    - Are you sure?
    - Certainly.
    - Excellent idea!
    - Greetings, %title%!
  large_tip:
    - Spreading the wealth, I see.
    - Very generous!
    - You will be a name to remember, %title%.
    - A true follower of Gaia.
    - Gaia will not forget this, I am sure.
    - A grand gesture, %title%.
    - Look at the muscles on you!
  burn:
    - Well, if you so desire.
    - Was this ill-received, perchance?
    - Wow, my pockets are always accepting donations.
    - Whoa! This burns bright.
  stats:
    - The riches of some people, incredible.
    - I bet you they all live in the capital.
    - There’s always bigger fish.
    - Do not compare yourself to others.
    - How do you rank, %title%?
    - An excellent start to the Age of Heroes.
  price:
    - Interesting indeed.
    - This explains the man that came in earlier...
    - Oh my! Are the Bank's reserves running dry?
    - Do you think Gaia weeps?
  get_gas:
    - A small blessing from Gaia herself.
    - Don't spend these all at once!
    - On the house!
    - Consider this a gift, %title%.