imports:
  - { resource: 'default.yml' }

# Token
token:
  default: "jewel"
  contract_address: "0x72Cb10C6bfA5624dD07Ef608027E366bd690048F"
  symbol: "JEWEL"
  decimals: 18
  network_explorer: "https://explorer.harmony.one/#"
  rpc_url: "https://api.s0.t.hmny.io"
alternative_tokens: []
tokens:
  jewel:
    contract_address: "0x72Cb10C6bfA5624dD07Ef608027E366bd690048F"
    symbol: "JEWEL"
    decimals: 18

locales:
  "896110833430577162": "es"
