imports:
  - { resource: 'default.yml' }

# Gas
gas:
  amount: 0.1
  max_balance: 0.01
  time_out: 31556926

# Tokens
token:
  default: "jewel"
  symbol: "JEWEL"
  decimals: 18
  thumbnail: "https://gateway.pinata.cloud/ipfs/QmRT1KRALWRbtwmmDVwGnwts3Qc6KCEwa7vtrWFvsY9DqB"
alternative_tokens: [ ]
tokens:
  jewel:
    symbol: "JEWEL"
    decimals: 18

# Network
network_explorer: "https://explorer.pops.one/#"
rpc_url: "https://api.s0.b.hmny.io"