imports:
  - { resource: 'default.yml' }

# Discord
roles:
  mod: '902630990407671859'
commands:
  blacklist: ''
  whitelist: ''
## ISO 639-1
locales:
  ### Chinese
  "000000000000000001": "zh"
  ### Japanese
  "000000000000000002": "ja"
  ### Italian
  "897510706537177139": "it"
  ### Malay
  "000000000000000004": "ms"
  ### Russian
  "000000000000000005": "ru"
  ### Spanish
  "000000000000000006": "es"
  ### Tagalog
  "000000000000000007": "tl"

# Gas
gas:
  amount: 0.1
  max_balance: 0.01
  time_out: 31556926

# Tokens
token:
  default: "jewel"
  symbol: "JEWEL"
  decimals: 18
  thumbnail: "https://gateway.pinata.cloud/ipfs/QmRT1KRALWRbtwmmDVwGnwts3Qc6KCEwa7vtrWFvsY9DqB"
alternative_tokens: [ ]
tokens:
  jewel:
    symbol: "JEWEL"
    address: "0x72Cb10C6bfA5624dD07Ef608027E366bd690048F"
    decimals: 18

# Network
network_explorer: "https://explorer.harmony.one/#"
rpc_url: "https://rpc.gainzstation.one/"